apiVersion: v1
kind: Service
metadata:
  name: wtas-service
spec:
  type: NodePort
  selector:
    app: wtas
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080  
